---
swagger: "2.0"
info:
  description: "This is a sample for swagger-maven-plugin"
  version: "v1"
  title: "Swagger Maven Plugin Sample"
host: "localhost:8080"
schemes:
- "http"
- "https"
paths:
  /api/actual/{ID_NUMBER}:
    get:
      operationId: "getActual"
      parameters:
      - name: "ID_NUMBER"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      - name: "startYear"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      - name: "startMonth"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Actual"
  /api/agreement/{ID_NUMBER}:
    get:
      operationId: "getAgreement"
      parameters:
      - name: "ID_NUMBER"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Agreement"
  /api/agreementList:
    get:
      operationId: "getAgreementList"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Agreements"
definitions:
  Actual:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      date:
        type: "string"
        format: "date"
  Agreement:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
  Agreements:
    type: "object"
    properties:
      agreementList:
        type: "array"
        items:
          $ref: "#/definitions/Agreement"
